// The image partial is nowhere included in other partials or pages because this snippet is generated by the asciidoc generator within Antora
import ImagePartial from '../partials/image.hbs';

// More on default export: https://storybook.js.org/docs/html/writing-stories/introduction#default-export
export default {
  title: 'Components/Image',
  // More on argTypes: https://storybook.js.org/docs/html/api/argtypes
  argTypes: {
    uri: { control: 'text' },
    alt: { control: 'text' },
    size: {
      control: { type: 'select' },
      options: ['small', 'medium', 'large'],
    },
  },
};

// More on component templates: https://storybook.js.org/docs/html/writing-stories/introduction#using-args
const Template = ({ uri, ...args }) => {
  return ImagePartial({ uri, ...args });
};

export const Small = Template.bind({});
// More on args: https://storybook.js.org/docs/html/writing-stories/args
Small.args = {
  uri: 'https://spotlight.tailwindui.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fplanetaria-design-system.d4cfce90.png&w=3840&q=75',
};

export const Medium = Template.bind({});
Medium.args = {
  uri: 'https://spotlight.tailwindui.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fplanetaria-design-system.d4cfce90.png&w=3840&q=75',
};

export const Large = Template.bind({});
Large.args = {
  uri: 'https://spotlight.tailwindui.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fplanetaria-design-system.d4cfce90.png&w=3840&q=75',
};
