name: Release
on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # First build by re-using the `ci.yaml` workflow
  build:
    uses: ./.github/workflows/ci.yaml
  # then publish a release of the site UI bundle
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ui-bundle.zip
      - uses: actions/download-artifact@v3
        with:
          name: ui-bundle
